services:
  floor-escape:
    build: .
    container_name: floor_escape
    restart: always
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user_floorgame:nvMrKdvM8nkqGGogWVM1oM8i@84.8.148.216:5432/db_floorgame
      - IS_REMOTE_SERVER=1
      - DB_STRICT=1
